steps:
  - name: 'docker/compose:1.26.2'
    args: ['up', '-d']
    env:
    - 'PROJECT_ID=$PROJECT_ID'
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
          "run",
          "deploy",
          "${_SERVICE_NAME}",
          "--image",
          "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}",
          "--region",
          "us-central1",
          "--platform",
          "managed",
          "--allow-unauthenticated",
      ]