steps:
  - name: 'docker/compose:1.26.2'
    args: ['up', '-d']
    env:
    - 'PROJECT_ID=$PROJECT_ID'
  - name: 'docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/promeddeluxe', '.']
images: ['gcr.io/$PROJECT_ID/promeddeluxe']