steps:
  - name: 'docker/compose:1.26.2'
    args: ['up', '-d']
    env:
    - 'PROJECT_ID=$PROJECT_ID'
  - name: 'gcr.io/cloud-builders/docker'
    args: [ "run", "--volume", "/workspace:/workspace", "--rm", "ubuntu", "ls", "-l", "/workspace" ]