steps:
- name: 'docker/compose:1.26.2'
  args: ['up', '-d']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
- name: 'gcr.io/cloud-builders/promed-288214'
  args: ['tag', 'promed-288214:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']