steps:
- name: 'docker/compose:1.26.2'
  args: ['up', '-d']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/docker:19.03.8', 'gcr.io/$PROJECT_ID/docker']