version: '2'

services:
  apache:
    build: 
      context: './apache/'
    image: ayoubbensakhria/apache
    restart: always
    ports:
      - "8090:80"
      - "444:443"
    networks: 
      - frontend
      - backend
    volumes:
      - ${PROJECT_ROOT}:/usr/local/apache2/htdocs
      - ./cert/:/usr/local/apache2/cert/
    depends_on:
      - php
      - mysql
    links:
      - mysql
    container_name: APACH
  php:
    build: 
      context: './php/'
    image: ayoubbensakhria/php
    restart: always
    networks: 
      - backend
    volumes:
      - ${PROJECT_ROOT}:/usr/local/apache2/htdocs
      - ./tmp:/usr/local/tmp
    links:
     - mysql
    container_name: PHP
  mysql:
    build: 
      context: './mysql/'
    image: ayoubbensakhria/mysql
    command: --default-authentication-plugin=mysql_native_password 
    restart: always
    networks:
      - backend
    ports:
      - "3304:3306"
    volumes:
      - data:/var/lib/mysql
# The default MySQL installation only creates the "root" administrative account
# create new users using docker-compose exec
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: MYSQL
  phpmyadmin:
    depends_on:
      - mysql
    links:
      - mysql
    image: ayoubbensakhria/phpmyadmin
    restart: always
    ports:
      - "8084:80"
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"   
    networks:
      - backend
    volumes:
      - /sessions
    container_name: PHPMYADMIN
networks: 
  backend:
  frontend:
volumes:
    data:
